export const iconMap: Record<string, any> = {
  "ac-unit": require("../../assets/imageIcons/ac-unit.png"),
  "ac-install": require("../../assets/imageIcons/ac-install.png"),
  "fan": require("../../assets/imageIcons/fan.png"),
  "lightbulb": require("../../assets/imageIcons/lightbulb.png"),
  "hot-water": require("../../assets/imageIcons/hot-water.png"),
  "gas": require("../../assets/imageIcons/gas.png"),
  "power": require("../../assets/imageIcons/power.png"),
  "wire": require("../../assets/imageIcons/wire.png"),
  "pipe-leak": require("../../assets/imageIcons/pipe-leak.png"),
  "filter": require("../../assets/imageIcons/filter.png"),
  "washing-machine": require("../../assets/imageIcons/washing-machine.png"),
  "fridge": require("../../assets/imageIcons/fridge.png"),
  "microwave": require("../../assets/imageIcons/microwave.png"),
  "tv": require("../../assets/imageIcons/tv.png"),
  "chimney": require("../../assets/imageIcons/chimney.png"),
  "shower": require("../../assets/imageIcons/shower.png"),
  "doorbell": require("../../assets/imageIcons/doorbell.png"),
  "switch": require("../../assets/imageIcons/switch.png"),
  "ceiling-fan": require("../../assets/imageIcons/ceiling-fan.png"),
  "cleaning": require("../../assets/imageIcons/cleaning.png"),
  "default": require("../../assets/imageIcons/default.png"),
};
