
// 🚀 Auto-generated by scripts/generateIconMap.js
// Do NOT edit this file manually.

import { ImageSourcePropType } from "react-native";

export type IconName = "2" | "4" | "5" | "ac-install" | "ac-unit" | "auto" | "ceiling-fan" | "chimney" | "cleaning" | "computer" | "doorbell" | "electric" | "fan" | "filter" | "fridge" | "gas" | "hot-water" | "iron-repair" | "lightbulb" | "microwave" | "painting" | "pipe-leak" | "plumbing" | "power" | "R.O. Services" | "shower" | "switch" | "Tap Service" | "TDS Checker" | "tv" | "washing-machine" | "wire" | "default";

export const iconMap: Record<IconName, ImageSourcePropType> = {
  "2": require("../../assets/imageIcons/2.png"),
  "4": require("../../assets/imageIcons/4.png"),
  "5": require("../../assets/imageIcons/5.png"),
  "ac-install": require("../../assets/imageIcons/ac-install.png"),
  "ac-unit": require("../../assets/imageIcons/ac-unit.png"),
  "auto": require("../../assets/imageIcons/auto.png"),
  "ceiling-fan": require("../../assets/imageIcons/ceiling-fan.png"),
  "chimney": require("../../assets/imageIcons/chimney.png"),
  "cleaning": require("../../assets/imageIcons/cleaning.png"),
  "computer": require("../../assets/imageIcons/computer.png"),
  "doorbell": require("../../assets/imageIcons/doorbell.png"),
  "electric": require("../../assets/imageIcons/electric.png"),
  "fan": require("../../assets/imageIcons/fan.png"),
  "filter": require("../../assets/imageIcons/filter.png"),
  "fridge": require("../../assets/imageIcons/fridge.png"),
  "gas": require("../../assets/imageIcons/gas.png"),
  "hot-water": require("../../assets/imageIcons/hot-water.png"),
  "iron-repair": require("../../assets/imageIcons/iron-repair.png"),
  "lightbulb": require("../../assets/imageIcons/lightbulb.png"),
  "microwave": require("../../assets/imageIcons/microwave.png"),
  "painting": require("../../assets/imageIcons/painting.png"),
  "pipe-leak": require("../../assets/imageIcons/pipe-leak.png"),
  "plumbing": require("../../assets/imageIcons/plumbing.png"),
  "power": require("../../assets/imageIcons/power.png"),
  "R.O. Services": require("../../assets/imageIcons/R.O. Services.png"),
  "shower": require("../../assets/imageIcons/shower.png"),
  "switch": require("../../assets/imageIcons/switch.png"),
  "Tap Service": require("../../assets/imageIcons/Tap Service.png"),
  "TDS Checker": require("../../assets/imageIcons/TDS Checker.png"),
  "tv": require("../../assets/imageIcons/tv.png"),
  "washing-machine": require("../../assets/imageIcons/washing-machine.png"),
  "wire": require("../../assets/imageIcons/wire.png"),
  "default": require("../../assets/imageIcons/default.png"),
};
